name: Bug Report
description: Report a bug to help us improve
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide clear details to help us reproduce and fix it.

  - type: dropdown
    id: os
    attributes:
      label: Target Operating System
      options:
        - Ubuntu 22.04 LTS
        - Ubuntu 20.04 LTS
        - Debian 12
        - Debian 11
        - CentOS 8
        - Rocky Linux
        - Red Hat Enterprise Linux
        - Alpine Linux
        - Other
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: "Python 3.11.x"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Linux Health Version
      description: What version are you using? (`linux_health --version` or check `__init__.py`)
      placeholder: "2.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what's not working
      placeholder: "When I run ... it fails with ..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Exact steps to reproduce the bug
      placeholder: |
        1. Run `python -m linux_health 192.168.1.100 user pass`
        2. ...
        3. Bug occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead
      placeholder: "It should scan successfully and generate a report"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "It crashes with error: ..."
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message or Log Output
      description: Full error message or relevant logs (use code fence)
      render: shell
      placeholder: |
        ```
        Traceback (most recent call last):
          File "...
        ```

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any other relevant environment info
      placeholder: |
        - Docker: Yes/No
        - Network: Direct/VPN/Proxy
        - SSH key type: RSA/ED25519
        - Target SSH version: ...

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical (complete failure)
        - High (major feature broken)
        - Medium (partial feature broken)
        - Low (minor issue, workaround exists)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked existing issues for duplicates
          required: true
        - label: I reviewed troubleshooting in README
          required: true
        - label: I'm using a supported Python version (3.11+)
          required: true
        - label: All tests pass on my system (`pytest tests/ -v`)
          required: false
