name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement! Please describe what you'd like to see and why.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like? Be specific.
      placeholder: "I'd like to add support for SIEM integration to export findings to..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem It Solves
      description: What problem or gap does this address?
      placeholder: "Currently, users have to manually export findings. This would automate..."
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits & Use Cases
      description: How would this benefit users? Include specific use cases.
      placeholder: |
        - Saves time for teams managing multiple hosts
        - Enables automated compliance reporting
        - Integrates with existing security workflows
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Suggested Implementation (Optional)
      description: If you have ideas on how to implement this, share them
      placeholder: |
        Could be done by:
        - Adding a new `--export-siem` flag
        - Creating a new reporter class
        - Supporting common SIEM APIs (Splunk, ELK, etc.)

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Core Scanning (new checks, improvements)
        - CLI/Interface
        - Reporting (formats, export)
        - Performance (speed, efficiency)
        - Integration (APIs, external tools)
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical (blocks major workflows)
        - High (significantly improves experience)
        - Medium (nice to have improvement)
        - Low (nice to have someday)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked existing issues/discussions for similar requests
          required: true
        - label: This doesn't duplicate existing functionality
          required: true
        - label: I searched [Discussions](../../discussions) for related conversations
          required: false
